// Preset-code fixtures for the decode/registry tests.
//
// REAL_PRESETS mirror src/popularPresets.ts (verified against shadcn's encoder).
// EDGE_PRESETS were generated by re-running the encode logic with specific
// configs to exercise branches the named presets don't cover (non-default
// radius, menuAccent=bold, chartColor != theme). They round-trip through
// decodePreset — see the encode/decode parity check in the repo history.

export const REAL_PRESETS = [
  { name: "Nova", code: "b2fA", font: "geist", style: "nova" },
  { name: "Vega", code: "bIkeymG", font: "inter", style: "vega" },
  { name: "Maia", code: "bbVKFP6", font: "figtree", style: "maia" },
  { name: "Lyra", code: "buFznsW", font: "jetbrains-mono", style: "lyra" },
  { name: "Mira", code: "b1D0eCA4", font: "inter", style: "mira" },
  { name: "Luma", code: "b1VlIttI", font: "inter", style: "luma" },
  { name: "Sera", code: "b4xFeBLg4O", font: "noto-sans", style: "sera" },
  { name: "Rhea", code: "b27GcrRo", font: "inter", style: "rhea" },
] as const;

// A v2 code whose only departure from the all-defaults baseline is radius=large
// (neutral base + neutral theme). Exercises the radius light-only branch.
export const RADIUS_LARGE_CODE = "b48";

// menuAccent=bold, theme=blue, chartColor=blue, neutral base. Exercises the
// bold-accent rewrite (accent <- primary) on both light and dark.
export const MENU_BOLD_CODE = "b1Ymqvgj2";

// theme=neutral but chartColor=blue (neutral base). Exercises the chart-color
// override pulling chart-1..5 from a different family.
export const CHART_OVERRIDE_CODE = "b1YmpVh4a";

// Minimal v1 ("a") code: all fields at index 0 (theme = neutral). Exercises the
// v1 upgrade path (fontHeading -> "inherit", chartColor via V1_CHART_COLOR_MAP
// so neutral -> blue charts).
export const V1_MINIMAL_CODE = "a0";

// Shape-valid (version + base62) but the bits overflow the encoded field range,
// so decodePreset must reject it.
export const OUT_OF_RANGE_CODE = "bzzzzzz";
